production:
  qiniu_access_key: O9nvaWGcvD86W7keehXRPhFNOWUXRi_gTQI8PscX  # 你的 qiniu AccessKey
  qiniu_secret_key: yegEe9Lf-lXuzBCN2owf_S6E7CUItude0dbWwCXC  # 你的 qiniu SecretKey
  qiniu_bucket: stock-finance-share  # 你的 qiniu bucket
  qiniu_bucket_domain: p4lebvpw1.bkt.clouddn.com  # 你的 qiniu bucket domain

development:
  qiniu_access_key: O9nvaWGcvD86W7keehXRPhFNOWUXRi_gTQI8PscX  # 你的 qiniu AccessKey
  qiniu_secret_key: yegEe9Lf-lXuzBCN2owf_S6E7CUItude0dbWwCXC  # 你的 qiniu SecretKey
  qiniu_bucket: stock-finance-share  # 你的 qiniu bucket
  qiniu_bucket_domain: p4lebvpw1.bkt.clouddn.com  # 你的 qiniu bucket domain
